# Generated by Django 5.2.1 on 2025-05-18 17:51

import redimers.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=120, validators=[redimers.models.validate])),
                ('createdAt', models.BigIntegerField(default=redimers.models.default_time)),
                ('important', models.BooleanField(default=False)),
            ],
        ),
    ]
